--- #YAML:1.0
name:               PDL
version:            2.4.8_001
abstract:           Perl Data Language
author:
    - PerlDL Developers (perldl@jach.hawaii.edu)
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Astro::FITS::Header:  0
    Convert::UU:          0
    Data::Dumper:         2.121
    File::Spec:           0.6
    Filter::Util::Call:   0
    Inline:               0.43
    OpenGL:               0.63
    Pod::Parser:          0
    Pod::Select:          0
    Storable:             1.03
    Text::Balanced:       0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
