---
abstract: 'Perl Data Language'
author:
  - 'PerlDL Developers (perldl@jach.hawaii.edu)'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112150'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: PDL
no_index:
  directory:
    - t
    - inc
requires:
  Astro::FITS::Header: 0
  Convert::UU: 0
  Data::Dumper: 2.121
  ExtUtils::MakeMaker: 6.31
  File::Map: 0.47
  File::Spec: 0.6
  File::Temp: 0
  Filter::Simple: 0.88
  Filter::Util::Call: 0
  Inline: 0.43
  Module::Compile: 0.23
  OpenGL: 0.65
  Pod::Parser: 0
  Pod::Select: 0
  Storable: 1.03
  Text::Balanced: 1.89
resources:
  bugtracker: http://sourceforge.net/tracker/?func=browse&group_id=612&atid=100612
  homepage: http://pdl.perl.org/
  repository: http://pdl.git.sourceforge.net/git/gitweb.cgi?p=pdl/pdl
version: 2.006_03
