--- #YAML:1.0
name:                PDL
version:             2.4.3_04
abstract:            Perl Data Language
license:             ~
author:              
    - PerlDL Developers (perldl@jach.hawaii.edu)
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
    Astro::FITS::Header:           0
    File::Spec:                    0.6
    Filter::Util::Call:            0
    Inline:                        0.43
    Text::Balanced:                0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
